// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    copy: typeof import('./src/components/TpTypingDetail copy.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TpButton: typeof import('./src/components/TpButton.vue')['default']
    TpFooter: typeof import('./src/components/TpFooter.vue')['default']
    TpInput: typeof import('./src/components/TpInput.vue')['default']
    TpReader: typeof import('./src/components/TpReader.vue')['default']
    TpReaderWord: typeof import('./src/components/TpReaderWord.vue')['default']
    TpShortcut: typeof import('./src/components/TpShortcut.vue')['default']
    TpTextarea: typeof import('./src/components/TpTextarea.vue')['default']
    TpTypingDetail: typeof import('./src/components/TpTypingDetail.vue')['default']
  }
}
